apiVersion: v2
name: aws-event-sources
version: 0.1.7
appVersion: 1.6.0
type: application
description: AWS Event Sources controller for Kubernetes
home: https://github.com/triggermesh/aws-event-sources
icon: https://raw.githubusercontent.com/triggermesh/aws-event-sources/master/images/klass-logo.png
keywords:
  - knative-eventing
  - sources
  - aws
  - triggermesh
  - serverless
maintainers:
  - name: sameersbn
  - name: antoineco
sources:
  - https://github.com/triggermesh/aws-event-sources
