#################
## AWS Sources ##
#################
steps:
## Build DynamoDB source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awsdynamodb:latest', '-f' ,'./awsdynamodb/Dockerfile', '.' ]

## Build SQS source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awssqs:latest', '-f' ,'./awssqs/Dockerfile', '.' ]

## Build CodeCommit source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awscodecommit:latest', '-f' ,'./awscodecommit/Dockerfile', '.' ]

## Build Cognito source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awscognito:latest', '-f' ,'./awscognito/Dockerfile', '.' ]

## Build Kinesis source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awskinesis:latest', '-f' ,'./awskinesis/Dockerfile', '.' ]

## Build Kinesis source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awss3:latest', '-f' ,'./awss3/Dockerfile', '.' ]

## Build SNS source
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/awssns:latest', '-f' ,'./awssns/Dockerfile', '.' ]


images: 
  - 'gcr.io/$PROJECT_ID/awssqs'
  - 'gcr.io/$PROJECT_ID/awsdynamodb'
  - 'gcr.io/$PROJECT_ID/awscognito'
  - 'gcr.io/$PROJECT_ID/awskinesis'
  - 'gcr.io/$PROJECT_ID/awscodecommit'
  - 'gcr.io/$PROJECT_ID/awss3'
  - 'gcr.io/$PROJECT_ID/awssns'
