steps:

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/awscodecommitsource/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/awscodecommitsource:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/awscodecommitsource/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/awscognitosource/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/awscognitosource:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/awscognitosource/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/awsdynamodbsource/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/awsdynamodbsource:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/awsdynamodbsource/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/awskinesissource/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/awskinesissource:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/awskinesissource/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=cmd/awssqssource/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/awssqssource:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/awssqssource/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

timeout: 600s

substitutions:
  _KANIKO_IMAGE_TAG: "latest"
  _KANIKO_NO_PUSH: "false"
  _KANIKO_USE_BUILD_CACHE: "true"
  _KANIKO_EXTRA_ARGS: ""

options:
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'N1_HIGHCPU_8'

tags:
  - aws-event-sources
