---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: awskinesis
spec:
  image: gcr.io/triggermesh/awskinesis:latest
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: awscreds
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: awscreds
          key: aws_secret_access_key
    - name: AWS_SECURE_TOKEN
      valueFrom:
        secretKeyRef:
          name: awscreds
          key: aws_secure_token
    - name: AWS_REGION
      value: us-east-1
    - name: STREAM
      value: stream_name